### ISSUE TITLE
Dart 2 compatibility

### ISSUE THREAD

**Issue by jesusrp98** [NeoDigi/igdb_wrapper#1]
Would it be possible to update this package to be Dart 2 compatible?

Here is a link about migrating a Dart 1 project to Dart 2: https://www.dartlang.org/dart-2#migration.

Please consider it, since it's not too difficult nor time consuming to update :)

**Comment by NeoDigi** [comment]
Ok, I'll check it out when I have time

**Comment by NeoDigi** [comment]
@jesusrp98 That should works now
